### PR TITLE
Adding reference for TSL docs

### PR DESCRIPTION
**Pull request by ruffsl**

### CODE REVIEW

**Comment by ehazlett** [comment]
Thanks!  While I agree this is best practice, it is technically not required.  Could we add both methods?  Regular TCP and TLS secured TCP?

**Comment by ehazlett** [comment]
Sorry -- I misread it!  Looks good!

**Comment by ehazlett** [comment]
LGTM

**Comment by ehazlett** [comment]
And just FYI, these are auto-deployed so these should be updated as soon as the image is built from the Docker Hub.  Thanks!

**Comment by ruffsl** [comment]
As an aside, is it at all possible to forward the unix socket directly using docker mounting, sort of in the same way that shipyard deploy uses it to start up the stack? Having to modify the Docker's defaults in the /etc folder and generating TSL certs to securely use TCP socket over http, while an educational process for me at first, is a bit of a hassle. 

Perhaps there is already issue for this? Or maybe there is a way to forward my port for my local engine's TCP socket to the necessary container in the deploy stack, so that I would not have to expose the socket to 0.0.0.0 and only to that of the local host, thus reducing the need for TSL.

Thanks!

**Pull request merged**
